remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Site Settings and SEO
locale: "en-US"
title: FAITH Project
title_separator: " | "
subtitle: Faith is Active Inference for Thinking Humans
description: Faith is Active Inference for Thinking Humans. Enhancing NPCs and Robotic Agents.
url: https://eclipsinglines.github.io
baseurl: /FAITH
repository: EclipsingLines/FAITH
author:
   name: EclipsingLines
   links:
     - url: https://linktr.ee/eclipsinglines
       icon: "fas fa-link"
       label: Linktree

# Theme and layout settings
header_type: base
footer:
  copyright: '&copy; <a href="https://linktr.ee/eclipsinglines" target="_blank">EclipsingLines</a> 2025'

github:
  is_project_page: true
  repository_url: "https://github.com/EclipsingLines/FAITH"

# Social links (optional)
social:
  github: EclipsingLines/FAITH

# FontAwesome
fa_version: "6"

# Search settings (optional)
search:
  provider: lunr
  label: Search
  landing_page: /search

# Navigation structure
navigation:
  - title: Home
    url: /
  - title: Overview
    url: /conceptual-overview
  - title: Models
    children:
      - title: Belief Model
        url: /belief-model
      - title: Perception Model
        url: /perception-model
      - title: Action Model
        url: /action-model
  - title: Implementation
    children:
      - title: Core Library
        url: /core-library
      - title: Engine Bindings
        url: /engine-bindings
      - title: Game-Specific Systems
        url: /game-specific-systems
  - title: Development
    children:
      - title: Architecture
        url: /proposed-architecture
      - title: Timeline
        url: /development-timeline
